version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-php_course}
      - DB_USERNAME=${DB_USER:-php_course}
      - DB_PASSWORD=${DB_PASS:-php_course}

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${WEB_PORT:-85}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend

  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - ${DB_PORT:-3308}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-php_course}
      - MYSQL_USER=${DB_USER:-php_course}
      - MYSQL_PASSWORD=${DB_PASS:-php_course}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-php_course}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8001:80
    environment:
      - MYSQL_USER=${DB_USER:-php_course}
      - MYSQL_PASSWORD=${DB_PASS:-php_course}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-php_course}
